name: build

on:
- push
- pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: docker build
      run: docker build -t this -f .circleci/Dockerfile .circleci/
    - name: jb install && make && zip
      run: |
        export WS=/go/src/github.com/kubernetes-monitoring/kubernetes-mixin
        docker run -v .:$WS:rw -w $WS this /bin/sh -c "jb install && make"
        zip kubernetes-monitoring-mixin.zip prometheus_alerts.yaml prometheus_rules.yaml lib/dashboards.jsonnet dashboards_out/
    - uses: actions/upload-artifact@v1
      with:
        name: kubernetes-monitoring-mixin.zip
        path: kubernetes-monitoring-mixin.zip
